//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pjcoordinador_PrRamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_RequisicionesBitacora
    {
        public int idBitacoraReq { get; set; }
        public Nullable<int> idRequisicion { get; set; }
        public Nullable<int> idEstadoAnterior { get; set; }
        public Nullable<int> idEstadoNuevo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string observacion { get; set; }
        public Nullable<int> idEmpleadoRegistra { get; set; }
    }
}
