//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pjcoordinador_PrRamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_requisiciones
    {
        public int idRequisicion { get; set; }
        public string detalleRequisicion { get; set; }
        public decimal cantidad { get; set; }
        public decimal precioUnitario { get; set; }
        public decimal total { get; set; }
        public string usuario { get; set; }
        public System.DateTime fechaSolicita { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaGraba { get; set; }
        public int idEmpleadoSolicita { get; set; }
        public int idEstado { get; set; }
    }
}
